### PR TITLE
Cloudera GCS connector Parcel: copy current folder content into the parcel

### LINKED ISSUE #209: Cloudera GCS connector parcel script does not copy directory files
When running the script, files in the same directory (e.g. the JSON key) are not copied over to the parcel folder.

In the following script:
`professional-services/tools/cloudera-parcel-gcsconnector/create_parcel.sh`

```
  # Download gcs connector jar and copy all folder content to parcel location
  # Set flag for further parcel file existence validation
  curl -o gcs-connector-hadoop2-latest.jar --fail ${GCSJAR_LINK} || GCSJAR_FLAG="0"

  # Validate if package downloaded properly
  if [[ ${GCSJAR_FLAG} = "0" ]]; then
    echo "Error: hadoop connector failed to download, check network connectivity or file/folder permissions"
    graceful_exit
  fi

  cp gcs-connector-hadoop2-latest.jar ${PARCEL_FULLNAME}/lib/hadoop/lib/
```

This part of the script only copies the jar file, but not other files in the folder.

I noticed that the correct code was removed in this [commit](https://github.com/GoogleCloudPlatform/professional-services/commit/6644bfa4fe966befe05ac5438f3839e53f85e985#diff-da08fbc0740e63da6962d55f1c8dd417), specifically:

```
##Download gcs connector jar and copy all folder content to parcel location
wget https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-latest.jar
if [[ $? -ne 0 ]]; then
   echo "Download GCS connector failed!"
   exit 1
fi

cp * ${filen^^}-$version/lib/hadoop/lib/

## Create parcel.json file required for parcel packaging
cat >>${filen^^}-$version/meta/parcel.json<< EOL
```

### PR DESCRIPTION
**Pull request by syvlabs**
Fixes #209 by copying not just the jar file, but all the files in the current directory. As per [the official guide](https://cloud.google.com/blog/products/storage-data-transfer/how-to-connect-clouderas-cdh-to-cloud-storage), the JSON file also has to be copied over to the parcel folder.

### CODE REVIEW

**Comment by syvlabs** [comment]
I signed it!

**Comment by syvlabs** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here (e.g. `I signed it!`) and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google.com/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fprofessional-services%2Fpull%2F210) for more info**.

I signed it!

**Comment by syvlabs** [comment]
Again tagging @yhqs540 for assistance, thanks!

File: tools/cloudera-parcel-gcsconnector/create_parcel.sh [hunk 1]
```diff
@@ -176,7 +176,7 @@ function main() {
     graceful_exit
   fi
 
-  cp gcs-connector-hadoop2-latest.jar ${PARCEL_FULLNAME}/lib/hadoop/lib/
+  cp * ${PARCEL_FULLNAME}/lib/hadoop/lib/
```
Comment (yhqs540) [inline tools/cloudera-parcel-gcsconnector/create_parcel.sh]: JSON key file is required for clusters that do not live on GCP. maybe only cp the gcs-connector-hadoop2-latest.jar and *.json instead of "*". These files will be replicated to every node of the cluster.

**Comment by yhqs540** [comment]
Sorry for the delay. Just one small change here.

**Comment by ryanmcdowell** [comment]
@syvlabs any update on the requested changes?

File: tools/cloudera-parcel-gcsconnector/create_parcel.sh [hunk 2]
```diff
@@ -177,7 +177,11 @@ function main() {
     graceful_exit
   fi
 
-  cp * ${PARCEL_FULLNAME}/lib/hadoop/lib/
+  # Copy GCS connector jar
+  cp gcs-connector-hadoop2-latest.jar ${PARCEL_FULLNAME}/lib/hadoop/lib/
+  
+  # Copy service account key file
+  cp *.json ${PARCEL_FULLNAME}/lib/hadoop/lib/
```
Comment (syvlabs) [inline tools/cloudera-parcel-gcsconnector/create_parcel.sh]: @yhqs540 sorry for the delay -- is this a good enough fix?

Comment (yhqs540) [reply tools/cloudera-parcel-gcsconnector/create_parcel.sh]: looks good. Thanks
